projects:
  conferencemanager:
    schemaPath: amplify/backend/api/conferencemanager/build/schema.graphql
    includes:
      - packages/api/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: packages/api/api.ts
        docsFilePath: packages/api
        region: us-east-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
