service: conference-manager

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: devProfile

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

functions:
  - ${file(src/ping/serverless.yml)}
  - ${file(src/organizer/events/serverless.yml)}
